apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-gitops-app

spec:
  replicas: 6

  selector:
    matchLabels:
      app: ai-gitops-app

  template:
    metadata:
      labels:
        app: ai-gitops-app

    spec:
      containers:
        - name: app
          image: ai-gitops-app:v3
          imagePullPolicy: Never

          ports:
            - containerPort: 3000

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5